### ISSUE TITLE
Ampere To Watt Converter

### ISSUE THREAD

**Issue by the0ne** [ferraridamiano/ConverterNOW#20] opened 2021-01-04 12:52 UTC
Would it be possible / make sense to integrate conversion (actually it's more a calculation than a conversation) like the following?

https://www.easycalculation.com/unit-conversion/amps-to-watt.php
https://www.easycalculation.com/unit-conversion/watt-to-amps.php

**Comment by ferraridamiano** [comment] 2021-01-04 13:26
Yes it can be possible, but at the moment this app is just a conversion tool and not a calculator. In the future I plan to add also a tools section. If you want to contribute, I'm open to any kind of PR! I'm closing this because it is a duplicate of #6.

**Closed by ferraridamiano** 2021-01-04 13:26 UTC
Labels: duplicate
