### ISSUE TITLE
[NewFeatureRequest] Let users set the units and converting rule

### ISSUE THREAD

**Issue by valuex** [ferraridamiano/ConverterNOW#233] opened 2023-07-01 12:28 UTC
Thanks for developing this wonderful application.
Is it possible to let the user set the units and corresponding  converting rules?
One possilbe idea is that,
Put the Units and the converting rule in one or multiple json file(s).
The json file structure file may look like this
``` json
[{
"UnitType": "length",
"BasicUnitFullName":"meter",
"BasicUnitShortName":"m",
"Units":[
{
"UnitFullName":"MiliMeter",
"UnitShortName":"mm",
"EqualsToBasicUnit":0.001
},
{
"UnitFullName":"KiloMeter",
"UnitShortName":"Km",
"EqualsToBasicUnit":1000
}]
}]
```

**Comment by ferraridamiano** [comment] 2023-07-01 12:36
Thank you for your suggestions, but I would like to keep the app as simple as possible to use. I'm closing this as a duplicate of #134. Feel free to comment there

**Closed** 2023-07-01 12:37 UTC
