### ISSUE TITLE
Update the website

### ISSUE THREAD

**Issue by milotype** [ferraridamiano/ConverterNOW#203] opened 2023-01-16 14:41 UTC
**Describe the bug**
The website is not up-to-date.

**To Reproduce**
1. ['Go to the Currency page'](https://converter-now.web.app/#/conversions/currencies)
2. See "Last update: 12/8/2021"
3. "Croatian Kuna" and some other currencies are still present, even though you've removed them in the [conversion file](https://github.com/ferraridamiano/ConverterNOW/blob/master/lib/models/conversions.dart).

**Expected behavior**
- Date should be updated for 2023. 
- Unsupported currencies shouldn't show up.

**Screenshots / gif**
![Currencies](https://user-images.githubusercontent.com/43657314/212703544-a5f8fad7-0824-419d-a55d-d496da7d8c65.png)

**Comment by ferraridamiano** [comment] 2023-01-16 14:51
Hi @milotype and thank you! Unfortunately it is not possible to update the currencies rates on the web (see issue #191). Their values are hard-coded on the web.
As you mentioned I recently removed some currencies because some of them no longer exists (kuna) and dome other are no longer supported by the european central bank (e.g. ruble).
I'm closing this as duplicate of #191

**Closed by ferraridamiano** 2023-01-16 14:51 UTC

**Comment by milotype** [comment] 2023-01-16 15:43
@ferraridamiano 
I've also seen the issue https://github.com/ferraridamiano/ConverterNOW/issues/191.

**Suggestions:**
1. Update the website so unsupported currencies don't show up.
2. Find a way to support converting currencies rates on a daily basis. If this isn't possible, I'd suggest to **completly** drop the support for converting currencies, because it makes no sense to convert on historic rates …
3. Maybe someone of the community can help you out with the issue of converting currencies on a daily basis!?

P.S. Sorry, I'm not a programmer, so I can't help on the issue of currency conversion!

**Comment by ferraridamiano** [comment] 2023-01-16 15:56
> Update the website so unsupported currencies don't show up.

The website will be updated the next release

> If this isn't possible, I'd suggest to completly drop the support for converting currencies, because it makes no sense to convert on historic rates

It makes sense but it will greatly increase the fragmentation between the platforms. I would like to do minimal changes to the code across different platforms.

> Maybe someone of the community can help you out with the issue of converting currencies on a daily basis!?

I'm always open to every PR!
